# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Scylidose
          template: classic
          base: header, activity, repositories
          config_display: large
          config_timezone: Canada/Eastern
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_ignored: Maintainer, Influencer, Inspirer
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: HTML, Assembly, Shell, ShaderLab, XSLT, Hack
          plugin_languages_skipped: Udemy, LES-MOIRES-2019, scylidose.github.io
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 15
          plugin_languages_threshold: 0%
          plugin_lines: yes
